on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]


jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "We appreciate your contribution. However, please note that this repository is intended to serve as sample code. It is not an actively maintained or ongoing project. Rather, we provide it as open-source code that you may adapt to your needs. You are welcome to fork this repo, up/downvote community forks, but we will not be accepting PRs. We ask that you use the [Camera Kit Community Forum](https://community.snap.com/snapar/categories/camera-kit) for help from Snap and the broader developer community."
          pr-message: "We appreciate your contribution. However, please note that this repository is intended to serve as sample code. It is not an actively maintained or ongoing project. Rather, we provide it as open-source code that you may adapt to your needs. You are welcome to fork this repo, up/downvote community forks, but we will not be accepting PRs. We ask that you use the [Camera Kit Community Forum](https://community.snap.com/snapar/categories/camera-kit) for help from Snap and the broader developer community."
          footer: ""
